name: build

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: VapourSynth Bundler
        shell: pwsh
        run: |
          $env:COMMIT_SHA = [String]($env:GITHUB_WORKFLOW_SHA[0..6] -join '')
          ni ./smShip.dummy.7z;exit 0; ./smCi.ps1 -Strip -UPX  -GITHUB_TOKEN ${{ secrets.GITHUB_TOKEN }}

      - uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          tag: ${{ env.COMMIT_SHA }}
          name: Nightly bundling
          files: |
            "smShip/VapourSynth.7z"
            "smShip/VapourSynth-Stripped.7z"
