name: build

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: VapourSynth Bundler
        shell: pwsh
        run: |
          $env:COMMIT_SHA = [String]($GITHUB_WORKFLOW_SHA[0..6] -join '')
          ni ./smShip.dummy.7z;exit 0; ./smCi.ps1 -Strip -UPX  -GITHUB_TOKEN ${{ secrets.GITHUB_TOKEN }}

      - uses: ncipollo/release-action@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Nightly bundling
          artifacts: "smShip/*.7z"
          token: ${{ env.COMMIT_SHA }}
          body: |
              Changes: https://github.com/herotc/hero-rotation/compare/${{ env.oldtag }}...${{ env.tag }}
