name: build

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: VapourSynth Bundler
        shell: pwsh
        run: ./smCi.ps1 -GITHUB_TOKEN ${{ secrets.GITHUB_TOKEN }} #-Strip -UPX 

      - uses: ncipollo/release-action@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: VapourSynth Bundler ${{ github.ref }}
          artifacts: "smBuild/smShip/*.7z"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true