name: build

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: VapourSynth Bundler
        shell: pwsh
        run: |
          $env:COMMIT_SHA = [String]($env:GITHUB_WORKFLOW_SHA[0..6] -join '')
          mkdir ./smShip;ni ./smShip/VapourSynth.7z;exit 0; ./smCi.ps1 -Strip -UPX  -GITHUB_TOKEN ${{ secrets.GITHUB_TOKEN }}
    
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::Nightly_$(date +"%Y.%m.%d_%H-%M")"

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ ${{ steps.tag.outputs.release_tag }} }}
          fail_on_unmatched_files: true
          files: |
            ./smShip/VapourSynth.7z
          
          
          #smShip/VapourSynth-Stripped.7z
