name: build

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: VapourSynth Bundler
        shell: pwsh
        run: Get-Item env:;Get-Variable;exit 1#./smCi.ps1 -Strip -UPX  -GITHUB_TOKEN ${{ secrets.GITHUB_TOKEN }}

      - uses: ncipollo/release-action@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Nightly bundling
          tag: ${{ env.GITHUB_RUN_ID }}
          artifacts: "smShip/*.7z"
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
              Changes: https://github.com/herotc/hero-rotation/compare/${{ env.oldtag }}...${{ env.tag }}
